# Generated by Django 5.2.6 on 2025-11-09 13:41

import Student.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
                ('semesterNo', models.IntegerField(help_text='Range is 1 - 8', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptID', models.IntegerField(validators=[Student.models.multiple_10])),
                ('deptName', models.CharField(max_length=100)),
                ('blockNo', models.CharField(max_length=1, validators=[Student.models.str_check])),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=9)),
                ('student_name', models.CharField(max_length=50)),
                ('CIANumber', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('mark', models.PositiveIntegerField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
                ('deptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.department')),
            ],
        ),
    ]
