# Generated by Django 5.2.6 on 2025-11-09 16:15

import Student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='deptID',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[Student.models.multiple_10]),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
