# Generated by Django 5.2.6 on 2025-11-09 12:15

import django.core.validators
import django.db.models.deletion
import seees_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('semesterNo', models.IntegerField(help_text='Must be between 1 and 8', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('year', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptID', models.IntegerField(primary_key=True, serialize=False, validators=[seees_app.models.validate_multiple_of_10])),
                ('deptName', models.CharField(max_length=100)),
                ('blockNo', models.CharField(max_length=100, validators=[seees_app.models.validate_block_letter])),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('CIANumber', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')])),
                ('mark', models.PositiveIntegerField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seees_app.course')),
                ('deptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seees_app.department')),
            ],
        ),
    ]
