# Generated by Django 5.2.6 on 2025-11-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dName', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('head_id', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programmeId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('programmeName', models.CharField(max_length=30)),
                ('No_of_semesters', models.PositiveSmallIntegerField(default=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('offering_deptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=120)),
                ('Course_credits', models.PositiveSmallIntegerField(default=3)),
                ('SemesterNo', models.PositiveSmallIntegerField(default=1)),
                ('DeptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.department')),
                ('programmeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registerNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('DOB', models.DateField()),
                ('join_date', models.CharField(max_length=10)),
                ('DeptID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Student.department')),
                ('programmeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Student.programme')),
            ],
        ),
        migrations.CreateModel(
            name='GradeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SemesterNo', models.PositiveSmallIntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
                ('deptID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Student.department')),
                ('ProgrammeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Student.programme')),
                ('registerNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
