# Generated by Django 5.2.6 on 2025-11-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_date',
            field=models.DateField(),
        ),
    ]
