# Generated by Django 5.2.6 on 2025-11-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_student_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesheet',
            name='cia1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='cia2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='cia3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='endsem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
