# Generated by Django 5.2.6 on 2025-10-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('booking_for', models.CharField(choices=[('flat', 'Flat'), ('HOUSE', 'Independent House')], max_length=10)),
                ('flat_type', models.CharField(choices=[('economy', 'Economy flat- 30 lakh rupees'), ('luxury', 'Luxury flat- 50 lakh rupees'), ('deluxe', 'Deluxe flat - 75 lakh rupees')], max_length=10)),
                ('house_type', models.CharField(choices=[('single', 'single house – 80 lakh'), ('duplex', 'duplex house – 1 crore')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
