# Generated by Django 5.2.6 on 2025-10-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Industry', 'Industry')], max_length=20)),
            ],
        ),
    ]
