# Generated by Django 5.2.6 on 2025-10-26 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dName', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('join_date', models.DateField()),
                ('salary', models.FloatField()),
                ('deptNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.department')),
            ],
        ),
    ]
